// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package index

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SeekRequest_Whence int32

const (
	SeekRequest_TOP     SeekRequest_Whence = 0
	SeekRequest_CURRENT SeekRequest_Whence = 1
	SeekRequest_BOTTOM  SeekRequest_Whence = 2
)

var SeekRequest_Whence_name = map[int32]string{
	0: "TOP",
	1: "CURRENT",
	2: "BOTTOM",
}

var SeekRequest_Whence_value = map[string]int32{
	"TOP":     0,
	"CURRENT": 1,
	"BOTTOM":  2,
}

func (x SeekRequest_Whence) String() string {
	return proto.EnumName(SeekRequest_Whence_name, int32(x))
}

func (SeekRequest_Whence) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{8, 0}
}

// Requests
type FileRequest struct {
	// Types that are valid to be assigned to Request:
	//	*FileRequest_Name
	//	*FileRequest_Open
	//	*FileRequest_Stat
	//	*FileRequest_Truncate
	//	*FileRequest_Read
	//	*FileRequest_ReadAt
	//	*FileRequest_Readdir
	//	*FileRequest_Readdirnames
	//	*FileRequest_Seek
	//	*FileRequest_Write
	//	*FileRequest_WriteAt
	Request              isFileRequest_Request `protobuf_oneof:"Request"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

type isFileRequest_Request interface {
	isFileRequest_Request()
}

type FileRequest_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type FileRequest_Open struct {
	Open *OpenRequest `protobuf:"bytes,2,opt,name=open,proto3,oneof"`
}

type FileRequest_Stat struct {
	Stat *StatRequest `protobuf:"bytes,3,opt,name=stat,proto3,oneof"`
}

type FileRequest_Truncate struct {
	Truncate *TruncateRequest `protobuf:"bytes,4,opt,name=truncate,proto3,oneof"`
}

type FileRequest_Read struct {
	Read *ReadRequest `protobuf:"bytes,5,opt,name=read,proto3,oneof"`
}

type FileRequest_ReadAt struct {
	ReadAt *ReadAtRequest `protobuf:"bytes,6,opt,name=readAt,proto3,oneof"`
}

type FileRequest_Readdir struct {
	Readdir *ReaddirRequest `protobuf:"bytes,7,opt,name=readdir,proto3,oneof"`
}

type FileRequest_Readdirnames struct {
	Readdirnames *ReaddirnamesRequest `protobuf:"bytes,8,opt,name=readdirnames,proto3,oneof"`
}

type FileRequest_Seek struct {
	Seek *SeekRequest `protobuf:"bytes,9,opt,name=seek,proto3,oneof"`
}

type FileRequest_Write struct {
	Write *WriteRequest `protobuf:"bytes,10,opt,name=write,proto3,oneof"`
}

type FileRequest_WriteAt struct {
	WriteAt *WriteAtRequest `protobuf:"bytes,11,opt,name=writeAt,proto3,oneof"`
}

func (*FileRequest_Name) isFileRequest_Request() {}

func (*FileRequest_Open) isFileRequest_Request() {}

func (*FileRequest_Stat) isFileRequest_Request() {}

func (*FileRequest_Truncate) isFileRequest_Request() {}

func (*FileRequest_Read) isFileRequest_Request() {}

func (*FileRequest_ReadAt) isFileRequest_Request() {}

func (*FileRequest_Readdir) isFileRequest_Request() {}

func (*FileRequest_Readdirnames) isFileRequest_Request() {}

func (*FileRequest_Seek) isFileRequest_Request() {}

func (*FileRequest_Write) isFileRequest_Request() {}

func (*FileRequest_WriteAt) isFileRequest_Request() {}

func (m *FileRequest) GetRequest() isFileRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *FileRequest) GetName() string {
	if x, ok := m.GetRequest().(*FileRequest_Name); ok {
		return x.Name
	}
	return ""
}

func (m *FileRequest) GetOpen() *OpenRequest {
	if x, ok := m.GetRequest().(*FileRequest_Open); ok {
		return x.Open
	}
	return nil
}

func (m *FileRequest) GetStat() *StatRequest {
	if x, ok := m.GetRequest().(*FileRequest_Stat); ok {
		return x.Stat
	}
	return nil
}

func (m *FileRequest) GetTruncate() *TruncateRequest {
	if x, ok := m.GetRequest().(*FileRequest_Truncate); ok {
		return x.Truncate
	}
	return nil
}

func (m *FileRequest) GetRead() *ReadRequest {
	if x, ok := m.GetRequest().(*FileRequest_Read); ok {
		return x.Read
	}
	return nil
}

func (m *FileRequest) GetReadAt() *ReadAtRequest {
	if x, ok := m.GetRequest().(*FileRequest_ReadAt); ok {
		return x.ReadAt
	}
	return nil
}

func (m *FileRequest) GetReaddir() *ReaddirRequest {
	if x, ok := m.GetRequest().(*FileRequest_Readdir); ok {
		return x.Readdir
	}
	return nil
}

func (m *FileRequest) GetReaddirnames() *ReaddirnamesRequest {
	if x, ok := m.GetRequest().(*FileRequest_Readdirnames); ok {
		return x.Readdirnames
	}
	return nil
}

func (m *FileRequest) GetSeek() *SeekRequest {
	if x, ok := m.GetRequest().(*FileRequest_Seek); ok {
		return x.Seek
	}
	return nil
}

func (m *FileRequest) GetWrite() *WriteRequest {
	if x, ok := m.GetRequest().(*FileRequest_Write); ok {
		return x.Write
	}
	return nil
}

func (m *FileRequest) GetWriteAt() *WriteAtRequest {
	if x, ok := m.GetRequest().(*FileRequest_WriteAt); ok {
		return x.WriteAt
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FileRequest_Name)(nil),
		(*FileRequest_Open)(nil),
		(*FileRequest_Stat)(nil),
		(*FileRequest_Truncate)(nil),
		(*FileRequest_Read)(nil),
		(*FileRequest_ReadAt)(nil),
		(*FileRequest_Readdir)(nil),
		(*FileRequest_Readdirnames)(nil),
		(*FileRequest_Seek)(nil),
		(*FileRequest_Write)(nil),
		(*FileRequest_WriteAt)(nil),
	}
}

type OpenRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{1}
}

func (m *OpenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenRequest.Unmarshal(m, b)
}
func (m *OpenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenRequest.Marshal(b, m, deterministic)
}
func (m *OpenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenRequest.Merge(m, src)
}
func (m *OpenRequest) XXX_Size() int {
	return xxx_messageInfo_OpenRequest.Size(m)
}
func (m *OpenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenRequest proto.InternalMessageInfo

func (m *OpenRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{2}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

type TruncateRequest struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TruncateRequest) Reset()         { *m = TruncateRequest{} }
func (m *TruncateRequest) String() string { return proto.CompactTextString(m) }
func (*TruncateRequest) ProtoMessage()    {}
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{3}
}

func (m *TruncateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TruncateRequest.Unmarshal(m, b)
}
func (m *TruncateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TruncateRequest.Marshal(b, m, deterministic)
}
func (m *TruncateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TruncateRequest.Merge(m, src)
}
func (m *TruncateRequest) XXX_Size() int {
	return xxx_messageInfo_TruncateRequest.Size(m)
}
func (m *TruncateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TruncateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TruncateRequest proto.InternalMessageInfo

func (m *TruncateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{4}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

type ReadAtRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAtRequest) Reset()         { *m = ReadAtRequest{} }
func (m *ReadAtRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAtRequest) ProtoMessage()    {}
func (*ReadAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{5}
}

func (m *ReadAtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAtRequest.Unmarshal(m, b)
}
func (m *ReadAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAtRequest.Marshal(b, m, deterministic)
}
func (m *ReadAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAtRequest.Merge(m, src)
}
func (m *ReadAtRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAtRequest.Size(m)
}
func (m *ReadAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAtRequest proto.InternalMessageInfo

func (m *ReadAtRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type ReaddirRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaddirRequest) Reset()         { *m = ReaddirRequest{} }
func (m *ReaddirRequest) String() string { return proto.CompactTextString(m) }
func (*ReaddirRequest) ProtoMessage()    {}
func (*ReaddirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{6}
}

func (m *ReaddirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaddirRequest.Unmarshal(m, b)
}
func (m *ReaddirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaddirRequest.Marshal(b, m, deterministic)
}
func (m *ReaddirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaddirRequest.Merge(m, src)
}
func (m *ReaddirRequest) XXX_Size() int {
	return xxx_messageInfo_ReaddirRequest.Size(m)
}
func (m *ReaddirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaddirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReaddirRequest proto.InternalMessageInfo

func (m *ReaddirRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ReaddirnamesRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaddirnamesRequest) Reset()         { *m = ReaddirnamesRequest{} }
func (m *ReaddirnamesRequest) String() string { return proto.CompactTextString(m) }
func (*ReaddirnamesRequest) ProtoMessage()    {}
func (*ReaddirnamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{7}
}

func (m *ReaddirnamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaddirnamesRequest.Unmarshal(m, b)
}
func (m *ReaddirnamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaddirnamesRequest.Marshal(b, m, deterministic)
}
func (m *ReaddirnamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaddirnamesRequest.Merge(m, src)
}
func (m *ReaddirnamesRequest) XXX_Size() int {
	return xxx_messageInfo_ReaddirnamesRequest.Size(m)
}
func (m *ReaddirnamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaddirnamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReaddirnamesRequest proto.InternalMessageInfo

func (m *ReaddirnamesRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SeekRequest struct {
	Offset               int64              `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Whence               SeekRequest_Whence `protobuf:"varint,2,opt,name=whence,proto3,enum=index.SeekRequest_Whence" json:"whence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SeekRequest) Reset()         { *m = SeekRequest{} }
func (m *SeekRequest) String() string { return proto.CompactTextString(m) }
func (*SeekRequest) ProtoMessage()    {}
func (*SeekRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{8}
}

func (m *SeekRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeekRequest.Unmarshal(m, b)
}
func (m *SeekRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeekRequest.Marshal(b, m, deterministic)
}
func (m *SeekRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeekRequest.Merge(m, src)
}
func (m *SeekRequest) XXX_Size() int {
	return xxx_messageInfo_SeekRequest.Size(m)
}
func (m *SeekRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SeekRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SeekRequest proto.InternalMessageInfo

func (m *SeekRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SeekRequest) GetWhence() SeekRequest_Whence {
	if m != nil {
		return m.Whence
	}
	return SeekRequest_TOP
}

type WriteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteRequest) Reset()         { *m = WriteRequest{} }
func (m *WriteRequest) String() string { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()    {}
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{9}
}

func (m *WriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteRequest.Unmarshal(m, b)
}
func (m *WriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteRequest.Marshal(b, m, deterministic)
}
func (m *WriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteRequest.Merge(m, src)
}
func (m *WriteRequest) XXX_Size() int {
	return xxx_messageInfo_WriteRequest.Size(m)
}
func (m *WriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteRequest proto.InternalMessageInfo

type WriteAtRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteAtRequest) Reset()         { *m = WriteAtRequest{} }
func (m *WriteAtRequest) String() string { return proto.CompactTextString(m) }
func (*WriteAtRequest) ProtoMessage()    {}
func (*WriteAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{10}
}

func (m *WriteAtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteAtRequest.Unmarshal(m, b)
}
func (m *WriteAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteAtRequest.Marshal(b, m, deterministic)
}
func (m *WriteAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteAtRequest.Merge(m, src)
}
func (m *WriteAtRequest) XXX_Size() int {
	return xxx_messageInfo_WriteAtRequest.Size(m)
}
func (m *WriteAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WriteAtRequest proto.InternalMessageInfo

// Responses
type FileInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime              int64    `protobuf:"varint,4,opt,name=modTime,proto3" json:"modTime,omitempty"`
	IsDir                bool     `protobuf:"varint,5,opt,name=isDir,proto3" json:"isDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileInfo) Reset()         { *m = FileInfo{} }
func (m *FileInfo) String() string { return proto.CompactTextString(m) }
func (*FileInfo) ProtoMessage()    {}
func (*FileInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{11}
}

func (m *FileInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileInfo.Unmarshal(m, b)
}
func (m *FileInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileInfo.Marshal(b, m, deterministic)
}
func (m *FileInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileInfo.Merge(m, src)
}
func (m *FileInfo) XXX_Size() int {
	return xxx_messageInfo_FileInfo.Size(m)
}
func (m *FileInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FileInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FileInfo proto.InternalMessageInfo

func (m *FileInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileInfo) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileInfo) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

func (m *FileInfo) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type FileResponse struct {
	// Types that are valid to be assigned to Response:
	//	*FileResponse_FileInfo
	//	*FileResponse_Read
	//	*FileResponse_Readdir
	//	*FileResponse_Readdirnames
	//	*FileResponse_Seek
	//	*FileResponse_Write
	Response             isFileResponse_Response `protobuf_oneof:"Response"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FileResponse) Reset()         { *m = FileResponse{} }
func (m *FileResponse) String() string { return proto.CompactTextString(m) }
func (*FileResponse) ProtoMessage()    {}
func (*FileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{12}
}

func (m *FileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileResponse.Unmarshal(m, b)
}
func (m *FileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileResponse.Marshal(b, m, deterministic)
}
func (m *FileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileResponse.Merge(m, src)
}
func (m *FileResponse) XXX_Size() int {
	return xxx_messageInfo_FileResponse.Size(m)
}
func (m *FileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileResponse proto.InternalMessageInfo

type isFileResponse_Response interface {
	isFileResponse_Response()
}

type FileResponse_FileInfo struct {
	FileInfo *FileInfo `protobuf:"bytes,1,opt,name=fileInfo,proto3,oneof"`
}

type FileResponse_Read struct {
	Read *ReadResponse `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type FileResponse_Readdir struct {
	Readdir *ReaddirResponse `protobuf:"bytes,3,opt,name=readdir,proto3,oneof"`
}

type FileResponse_Readdirnames struct {
	Readdirnames *ReaddirnamesResponse `protobuf:"bytes,4,opt,name=readdirnames,proto3,oneof"`
}

type FileResponse_Seek struct {
	Seek *SeekResponse `protobuf:"bytes,5,opt,name=seek,proto3,oneof"`
}

type FileResponse_Write struct {
	Write *WriteResponse `protobuf:"bytes,6,opt,name=write,proto3,oneof"`
}

func (*FileResponse_FileInfo) isFileResponse_Response() {}

func (*FileResponse_Read) isFileResponse_Response() {}

func (*FileResponse_Readdir) isFileResponse_Response() {}

func (*FileResponse_Readdirnames) isFileResponse_Response() {}

func (*FileResponse_Seek) isFileResponse_Response() {}

func (*FileResponse_Write) isFileResponse_Response() {}

func (m *FileResponse) GetResponse() isFileResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *FileResponse) GetFileInfo() *FileInfo {
	if x, ok := m.GetResponse().(*FileResponse_FileInfo); ok {
		return x.FileInfo
	}
	return nil
}

func (m *FileResponse) GetRead() *ReadResponse {
	if x, ok := m.GetResponse().(*FileResponse_Read); ok {
		return x.Read
	}
	return nil
}

func (m *FileResponse) GetReaddir() *ReaddirResponse {
	if x, ok := m.GetResponse().(*FileResponse_Readdir); ok {
		return x.Readdir
	}
	return nil
}

func (m *FileResponse) GetReaddirnames() *ReaddirnamesResponse {
	if x, ok := m.GetResponse().(*FileResponse_Readdirnames); ok {
		return x.Readdirnames
	}
	return nil
}

func (m *FileResponse) GetSeek() *SeekResponse {
	if x, ok := m.GetResponse().(*FileResponse_Seek); ok {
		return x.Seek
	}
	return nil
}

func (m *FileResponse) GetWrite() *WriteResponse {
	if x, ok := m.GetResponse().(*FileResponse_Write); ok {
		return x.Write
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FileResponse_FileInfo)(nil),
		(*FileResponse_Read)(nil),
		(*FileResponse_Readdir)(nil),
		(*FileResponse_Readdirnames)(nil),
		(*FileResponse_Seek)(nil),
		(*FileResponse_Write)(nil),
	}
}

type ReadResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{13}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type ReaddirResponse struct {
	FileInfo             []*FileInfo `protobuf:"bytes,1,rep,name=fileInfo,proto3" json:"fileInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReaddirResponse) Reset()         { *m = ReaddirResponse{} }
func (m *ReaddirResponse) String() string { return proto.CompactTextString(m) }
func (*ReaddirResponse) ProtoMessage()    {}
func (*ReaddirResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{14}
}

func (m *ReaddirResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaddirResponse.Unmarshal(m, b)
}
func (m *ReaddirResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaddirResponse.Marshal(b, m, deterministic)
}
func (m *ReaddirResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaddirResponse.Merge(m, src)
}
func (m *ReaddirResponse) XXX_Size() int {
	return xxx_messageInfo_ReaddirResponse.Size(m)
}
func (m *ReaddirResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaddirResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReaddirResponse proto.InternalMessageInfo

func (m *ReaddirResponse) GetFileInfo() []*FileInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

type ReaddirnamesResponse struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaddirnamesResponse) Reset()         { *m = ReaddirnamesResponse{} }
func (m *ReaddirnamesResponse) String() string { return proto.CompactTextString(m) }
func (*ReaddirnamesResponse) ProtoMessage()    {}
func (*ReaddirnamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{15}
}

func (m *ReaddirnamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaddirnamesResponse.Unmarshal(m, b)
}
func (m *ReaddirnamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaddirnamesResponse.Marshal(b, m, deterministic)
}
func (m *ReaddirnamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaddirnamesResponse.Merge(m, src)
}
func (m *ReaddirnamesResponse) XXX_Size() int {
	return xxx_messageInfo_ReaddirnamesResponse.Size(m)
}
func (m *ReaddirnamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaddirnamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReaddirnamesResponse proto.InternalMessageInfo

func (m *ReaddirnamesResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type SeekResponse struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeekResponse) Reset()         { *m = SeekResponse{} }
func (m *SeekResponse) String() string { return proto.CompactTextString(m) }
func (*SeekResponse) ProtoMessage()    {}
func (*SeekResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{16}
}

func (m *SeekResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeekResponse.Unmarshal(m, b)
}
func (m *SeekResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeekResponse.Marshal(b, m, deterministic)
}
func (m *SeekResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeekResponse.Merge(m, src)
}
func (m *SeekResponse) XXX_Size() int {
	return xxx_messageInfo_SeekResponse.Size(m)
}
func (m *SeekResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SeekResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SeekResponse proto.InternalMessageInfo

func (m *SeekResponse) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type WriteResponse struct {
	BytesWritten         int32    `protobuf:"varint,1,opt,name=bytesWritten,proto3" json:"bytesWritten,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteResponse) Reset()         { *m = WriteResponse{} }
func (m *WriteResponse) String() string { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()    {}
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f750e0f7889345b5, []int{17}
}

func (m *WriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteResponse.Unmarshal(m, b)
}
func (m *WriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteResponse.Marshal(b, m, deterministic)
}
func (m *WriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteResponse.Merge(m, src)
}
func (m *WriteResponse) XXX_Size() int {
	return xxx_messageInfo_WriteResponse.Size(m)
}
func (m *WriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WriteResponse proto.InternalMessageInfo

func (m *WriteResponse) GetBytesWritten() int32 {
	if m != nil {
		return m.BytesWritten
	}
	return 0
}

func init() {
	proto.RegisterEnum("index.SeekRequest_Whence", SeekRequest_Whence_name, SeekRequest_Whence_value)
	proto.RegisterType((*FileRequest)(nil), "index.FileRequest")
	proto.RegisterType((*OpenRequest)(nil), "index.OpenRequest")
	proto.RegisterType((*StatRequest)(nil), "index.StatRequest")
	proto.RegisterType((*TruncateRequest)(nil), "index.TruncateRequest")
	proto.RegisterType((*ReadRequest)(nil), "index.ReadRequest")
	proto.RegisterType((*ReadAtRequest)(nil), "index.ReadAtRequest")
	proto.RegisterType((*ReaddirRequest)(nil), "index.ReaddirRequest")
	proto.RegisterType((*ReaddirnamesRequest)(nil), "index.ReaddirnamesRequest")
	proto.RegisterType((*SeekRequest)(nil), "index.SeekRequest")
	proto.RegisterType((*WriteRequest)(nil), "index.WriteRequest")
	proto.RegisterType((*WriteAtRequest)(nil), "index.WriteAtRequest")
	proto.RegisterType((*FileInfo)(nil), "index.FileInfo")
	proto.RegisterType((*FileResponse)(nil), "index.FileResponse")
	proto.RegisterType((*ReadResponse)(nil), "index.ReadResponse")
	proto.RegisterType((*ReaddirResponse)(nil), "index.ReaddirResponse")
	proto.RegisterType((*ReaddirnamesResponse)(nil), "index.ReaddirnamesResponse")
	proto.RegisterType((*SeekResponse)(nil), "index.SeekResponse")
	proto.RegisterType((*WriteResponse)(nil), "index.WriteResponse")
}

func init() {
	proto.RegisterFile("index.proto", fileDescriptor_f750e0f7889345b5)
}

var fileDescriptor_f750e0f7889345b5 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0xf3, 0xe3, 0x24, 0x63, 0x27, 0x8d, 0xa6, 0xf9, 0x2a, 0x7f, 0xe5, 0xa6, 0xac, 0x44,
	0x49, 0x49, 0x89, 0x68, 0xca, 0x35, 0x22, 0x05, 0x2a, 0xb8, 0x80, 0xa0, 0x6d, 0x50, 0xaf, 0xd3,
	0x78, 0x23, 0xac, 0x12, 0x3b, 0xd8, 0x5b, 0x0a, 0x5c, 0xf3, 0x02, 0xbc, 0x13, 0x0f, 0x86, 0xf6,
	0xc7, 0xf6, 0x6e, 0x70, 0xaf, 0xb2, 0x33, 0x39, 0x67, 0x33, 0x33, 0x67, 0xce, 0x06, 0xbc, 0x28,
	0x0e, 0xd9, 0xf7, 0xf1, 0x26, 0x4d, 0x78, 0x82, 0x4d, 0x19, 0x90, 0xdf, 0x0d, 0xf0, 0x2e, 0xa2,
	0x2f, 0x8c, 0xb2, 0xaf, 0xb7, 0x2c, 0xe3, 0x38, 0x80, 0x46, 0xbc, 0x58, 0xb3, 0xc0, 0x39, 0x74,
	0x86, 0x9d, 0xb7, 0x3b, 0x54, 0x46, 0x38, 0x84, 0x46, 0xb2, 0x61, 0x71, 0x50, 0x3b, 0x74, 0x86,
	0xde, 0x04, 0xc7, 0xea, 0xa2, 0xd9, 0x86, 0xc5, 0x9a, 0x27, 0x90, 0x02, 0x21, 0x90, 0x19, 0x5f,
	0xf0, 0xa0, 0x6e, 0x21, 0x2f, 0xf9, 0x82, 0x1b, 0x48, 0x81, 0xc0, 0xe7, 0xd0, 0xe6, 0xe9, 0x6d,
	0xbc, 0x5c, 0x70, 0x16, 0x34, 0x24, 0x7a, 0x5f, 0xa3, 0xe7, 0x3a, 0x5d, 0x32, 0x0a, 0xa4, 0xb8,
	0x3f, 0x65, 0x8b, 0x30, 0x68, 0x5a, 0xf7, 0x53, 0xb6, 0x08, 0x8d, 0xfb, 0x05, 0x02, 0xc7, 0xe0,
	0x8a, 0xcf, 0x29, 0x0f, 0x5c, 0x89, 0x1d, 0x18, 0xd8, 0xa9, 0x51, 0x8d, 0x46, 0xe1, 0x29, 0xb4,
	0xc4, 0x29, 0x8c, 0xd2, 0xa0, 0x25, 0x09, 0xff, 0x19, 0x84, 0x30, 0x4a, 0x4b, 0x46, 0x8e, 0xc3,
	0x97, 0xe0, 0xeb, 0xa3, 0x98, 0x52, 0x16, 0xb4, 0x25, 0xef, 0xc0, 0xe6, 0xc9, 0xaf, 0x4a, 0xb2,
	0xc5, 0x90, 0xe3, 0x62, 0xec, 0x26, 0xe8, 0xd8, 0xe3, 0x62, 0xec, 0xc6, 0x1c, 0x17, 0x63, 0x37,
	0x38, 0x82, 0xe6, 0x5d, 0x1a, 0x71, 0x16, 0x80, 0x84, 0xee, 0x69, 0xe8, 0x95, 0xc8, 0x95, 0x58,
	0x85, 0x11, 0xbd, 0xc8, 0xc3, 0x94, 0x07, 0x9e, 0xd5, 0xcb, 0x95, 0xca, 0x1a, 0xbd, 0x68, 0xdc,
	0x79, 0x07, 0x5a, 0x3a, 0x4b, 0x1e, 0x82, 0x67, 0x48, 0x8b, 0x68, 0xae, 0x84, 0x5a, 0x08, 0xd2,
	0x05, 0xcf, 0xd0, 0x94, 0x3c, 0x82, 0xdd, 0x2d, 0xd1, 0x04, 0x2b, 0x8b, 0x7e, 0x2a, 0x56, 0x9d,
	0xca, 0xb3, 0x60, 0x19, 0x4a, 0x91, 0xc7, 0xd0, 0xb5, 0xc4, 0xc0, 0x7d, 0x70, 0x93, 0xd5, 0x2a,
	0x63, 0x5c, 0xb3, 0x74, 0x44, 0x8e, 0xa0, 0x67, 0x8b, 0x80, 0x03, 0x68, 0x2e, 0x93, 0xdb, 0x58,
	0x01, 0x9b, 0x54, 0x05, 0x64, 0x04, 0x7b, 0x15, 0x43, 0xbf, 0x07, 0xfc, 0xcb, 0x01, 0xcf, 0x18,
	0xf4, 0x7d, 0x3f, 0x8e, 0xa7, 0xe0, 0xde, 0x7d, 0x66, 0xf1, 0x92, 0xc9, 0xed, 0xef, 0x4d, 0xfe,
	0xff, 0x57, 0xa4, 0xf1, 0x95, 0x04, 0x50, 0x0d, 0x24, 0x4f, 0xc0, 0x55, 0x19, 0x6c, 0x41, 0x7d,
	0x3e, 0xfb, 0xd8, 0xdf, 0x41, 0x0f, 0x5a, 0xaf, 0x3e, 0x51, 0xfa, 0xe6, 0xc3, 0xbc, 0xef, 0x20,
	0x80, 0x7b, 0x3e, 0x9b, 0xcf, 0x67, 0xef, 0xfb, 0x35, 0xd2, 0x03, 0xdf, 0xd4, 0x90, 0xf4, 0xa1,
	0x67, 0x8b, 0x44, 0xbe, 0x41, 0x5b, 0x38, 0xf4, 0x5d, 0xbc, 0x4a, 0xaa, 0xb4, 0x28, 0x26, 0x5d,
	0x2b, 0x27, 0x2d, 0x72, 0xeb, 0x24, 0x64, 0xd2, 0x86, 0x5d, 0x2a, 0xcf, 0x18, 0x40, 0x6b, 0x9d,
	0x84, 0xf3, 0x68, 0xad, 0xfc, 0x56, 0xa7, 0x79, 0x28, 0x06, 0x14, 0x65, 0xaf, 0xa3, 0x54, 0xba,
	0xaa, 0x4d, 0x55, 0x40, 0xfe, 0xd4, 0xc0, 0x57, 0x4f, 0x43, 0xb6, 0x49, 0xe2, 0x8c, 0xe1, 0x53,
	0x68, 0xaf, 0x74, 0x21, 0xb2, 0x00, 0x6f, 0xb2, 0xab, 0x67, 0x91, 0xd7, 0x27, 0xac, 0x9a, 0x43,
	0xf0, 0x58, 0x5b, 0xb5, 0x66, 0x2d, 0xac, 0x5a, 0x00, 0x75, 0x63, 0xe1, 0xd5, 0x49, 0xe9, 0xbd,
	0xba, 0xf5, 0x14, 0x14, 0xb2, 0x17, 0x84, 0xc2, 0x7c, 0xd3, 0x2d, 0xf3, 0xa9, 0x37, 0xe4, 0x41,
	0xa5, 0xf9, 0x0a, 0xb6, 0xed, 0xbe, 0x63, 0xed, 0xbe, 0xa6, 0x55, 0xa1, 0x12, 0xb6, 0xac, 0x50,
	0xda, 0xef, 0x24, 0xb7, 0x9f, 0xfd, 0x98, 0x68, 0xe9, 0x0a, 0xb0, 0x02, 0x9d, 0x03, 0xb4, 0xf3,
	0x24, 0x19, 0x82, 0x6f, 0xf6, 0x2c, 0x64, 0x58, 0x26, 0x31, 0x67, 0x7a, 0x1f, 0x7d, 0x9a, 0x87,
	0xe4, 0x05, 0xec, 0x6e, 0xf5, 0x8b, 0x23, 0x6b, 0xe4, 0xf5, 0x8a, 0x91, 0x97, 0x03, 0x27, 0x27,
	0x30, 0xa8, 0x6a, 0x5b, 0xc8, 0xab, 0x46, 0x24, 0x6e, 0xe8, 0x50, 0x15, 0x90, 0x23, 0xf0, 0xcd,
	0x4e, 0xef, 0x35, 0xdf, 0x19, 0x74, 0xad, 0x2e, 0x91, 0x80, 0x7f, 0xfd, 0x83, 0xb3, 0x4c, 0x64,
	0x39, 0x8b, 0xb5, 0xab, 0xac, 0xdc, 0x64, 0x05, 0xb5, 0x8b, 0x4b, 0x1c, 0x41, 0x43, 0xbc, 0x12,
	0x88, 0x46, 0xcd, 0x7a, 0xab, 0x0f, 0xb6, 0xfb, 0xc0, 0x33, 0x68, 0x88, 0x57, 0xa7, 0x12, 0xbc,
	0x67, 0xe5, 0x54, 0x1d, 0x43, 0xe7, 0x99, 0x73, 0xed, 0xca, 0x3f, 0xb3, 0xb3, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x95, 0x76, 0x54, 0x15, 0xdb, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FSClient is the client API for FS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FSClient interface {
	Stat(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileInfo, error)
	Open(ctx context.Context, opts ...grpc.CallOption) (FS_OpenClient, error)
}

type fSClient struct {
	cc grpc.ClientConnInterface
}

func NewFSClient(cc grpc.ClientConnInterface) FSClient {
	return &fSClient{cc}
}

func (c *fSClient) Stat(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*FileInfo, error) {
	out := new(FileInfo)
	err := c.cc.Invoke(ctx, "/index.FS/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fSClient) Open(ctx context.Context, opts ...grpc.CallOption) (FS_OpenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FS_serviceDesc.Streams[0], "/index.FS/Open", opts...)
	if err != nil {
		return nil, err
	}
	x := &fSOpenClient{stream}
	return x, nil
}

type FS_OpenClient interface {
	Send(*FileRequest) error
	Recv() (*FileResponse, error)
	grpc.ClientStream
}

type fSOpenClient struct {
	grpc.ClientStream
}

func (x *fSOpenClient) Send(m *FileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fSOpenClient) Recv() (*FileResponse, error) {
	m := new(FileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FSServer is the server API for FS service.
type FSServer interface {
	Stat(context.Context, *FileRequest) (*FileInfo, error)
	Open(FS_OpenServer) error
}

// UnimplementedFSServer can be embedded to have forward compatible implementations.
type UnimplementedFSServer struct {
}

func (*UnimplementedFSServer) Stat(ctx context.Context, req *FileRequest) (*FileInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedFSServer) Open(srv FS_OpenServer) error {
	return status.Errorf(codes.Unimplemented, "method Open not implemented")
}

func RegisterFSServer(s *grpc.Server, srv FSServer) {
	s.RegisterService(&_FS_serviceDesc, srv)
}

func _FS_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FSServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.FS/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FSServer).Stat(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FS_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FSServer).Open(&fSOpenServer{stream})
}

type FS_OpenServer interface {
	Send(*FileResponse) error
	Recv() (*FileRequest, error)
	grpc.ServerStream
}

type fSOpenServer struct {
	grpc.ServerStream
}

func (x *fSOpenServer) Send(m *FileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fSOpenServer) Recv() (*FileRequest, error) {
	m := new(FileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "index.FS",
	HandlerType: (*FSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _FS_Stat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _FS_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "index.proto",
}
